// constants/mockModels.ts
import type { ModelDetail } from '~/types/model';

export const mockModels: ModelDetail[] = [
  {
    id: '1',
    title: '기억의 지속',
    image: require('~/assets/images/1.png'),
    artist: '살바도르 달리',
    liked: true,
    likes: 42,
    relatedImages: [
      require('~/assets/images/review1.png'),
      require('~/assets/images/review2.png'),
      require('~/assets/images/review3.png'),
      require('~/assets/images/review4.png'),
    ],
    reviews: [
      {
        id: 'r1',
        nickname: '시간여행자',
        comment: '달리의 감성이 그대로 묻어있어요. 멋집니다!',
        date: '2025.03.20',
        image: require('~/assets/images/review1.png'),
      },
      {
        id: 'r2',
        nickname: '이클립스',
        comment: '너무 좋아요!!',
        date: '2025.03.19',
        image: require('~/assets/images/review2.png'),
      },
      {
        id: 'r3',
        nickname: '모네마네미네',
        comment: '화가의 화풍을 적용하니까 사진 퀄리티가 달라졌어요! 감사합니당 ㅎㅎ',
        date: '2025.03.15',
        image: require('~/assets/images/review3.png'),
      },
    ],
  },
  {
    id: '2',
    title: '그랑드자트섬의 일요일 오후',
    image: require('~/assets/images/2.png'),
    artist: '조르주 쇠라',
    liked: false,
    likes: 33,
    relatedImages: [require('~/assets/images/review1.png'), require('~/assets/images/review2.png')],
    reviews: [
      {
        id: 'r2',
        nickname: '이클릴스',
        comment: '너무 좋아요!',
        date: '2025.03.19',
        image: require('~/assets/images/review1.png'),
      },
      {
        id: 'r3',
        nickname: '모네미네미네',
        comment: '화풍을 적용하니 사진이 다르게 느껴져요!',
        date: '2025.03.19',
        image: require('~/assets/images/review2.png'),
      },
    ],
  },
  {
    id: '3',
    title: '물랭 드 라 갈레트의 무도회',
    image: require('~/assets/images/3.png'),
    artist: '르누아르',
    liked: true,
    likes: 18,
    relatedImages: [],
    reviews: [],
  },
  {
    id: '4',
    title: '절규',
    image: require('~/assets/images/4.png'),
    artist: '에드바르 뭉크',
    liked: false,
    likes: 25,
    relatedImages: [],
    reviews: [],
  },
  {
    id: '5',
    title: '파리 거리, 비오는 날',
    image: require('~/assets/images/5.png'),
    artist: '귀스타브 카유보트',
    liked: false,
    likes: 12,
    relatedImages: [],
    reviews: [],
  },
  {
    id: '6',
    title: '우산 든 여인',
    image: require('~/assets/images/6.png'),
    artist: '클로드 모네',
    liked: true,
    likes: 58,
    relatedImages: [require('~/assets/images/review3.png'), require('~/assets/images/review2.png')],
    reviews: [
      {
        id: 'r4',
        nickname: '비오는날',
        comment: '이 느낌 너무 좋아요 ☔️',
        date: '2025.03.18',
        image: require('~/assets/images/review4.png'),
      },
    ],
  },
];
